import { Injectable, Logger, Optional } from '@nestjs/common';
import * as puppeteer from 'puppeteer';
import * as ejs from 'ejs';
import { S3Service } from '../s3/s3.service';
import type { Queue } from 'bull';
import { InjectQueue } from '@nestjs/bull';

@Injectable()
export class DocumentsService {
  private readonly logger = new Logger(DocumentsService.name);

  constructor(
    private s3: S3Service,
    @Optional() @InjectQueue('pdf') private pdfQueue?: Queue
  ) {}

  async generateWorkOrderPdf(
    auctionId: string,
    clientName: string,
    vendorName: string,
    vendorAddress: string,
    auctionTitle: string,
    totalWeight: number,
    winningAmount: number,
  ): Promise<string> {
    const s3Key = `work-orders/${auctionId}/WO-${Date.now()}.pdf`;

    const payload = {
      auctionId, clientName, vendorName, vendorAddress, auctionTitle, totalWeight, winningAmount, s3Key
    };

    if (this.pdfQueue) {
      await this.pdfQueue.add('generateWorkOrder', payload, {
        attempts: 3,
        backoff: { type: 'exponential', delay: 5000 },
      });
      this.logger.log(`Queued PDF generation for Auction ${auctionId}`);
    } else {
      this.logger.warn(`PDF Queue not found. Running generation synchronously for Auction ${auctionId}`);
      await this.executeGenerateWorkOrderPdf(payload);
    }
    
    // We return the expected key immediately so the caller can save the DB record.
    // The background job will fulfill the file at this key location shortly after.
    return s3Key;
  }

  async executeGenerateWorkOrderPdf(payload: any): Promise<string> {
    const { auctionId, clientName, vendorName, vendorAddress, auctionTitle, totalWeight, winningAmount, s3Key } = payload;
    this.logger.log(`Executing Work Order Generation for Auction ${auctionId}`);

    const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Work Order - ${auctionId}</title>
        <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
            h1 { color: #1E8E3E; text-align: center; border-bottom: 2px solid #1E8E3E; padding-bottom: 10px; }
            .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
            .details { width: 48%; }
            .section { margin-top: 30px; }
            .section-title { font-size: 18px; font-weight: bold; background-color: #f5f7fa; padding: 10px; margin-bottom: 15px; }
            table { width: 100%; border-collapse: collapse; margin-top: 15px; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            th { background-color: #f5f7fa; }
            .footer { margin-top: 60px; border-top: 1px solid #ddd; padding-top: 20px; font-size: 12px; color: #777; text-align: center; }
            .signature-box { margin-top: 50px; display: flex; justify-content: space-between; }
            .sign-line { border-top: 1px solid #333; width: 200px; text-align: center; padding-top: 5px; }
        </style>
    </head>
    <body>
        <h1>OFFICIAL WORK ORDER</h1>
        
        <div class="header">
            <div class="details">
                <p><strong>Date:</strong> <%= new Date().toLocaleDateString() %></p>
                <p><strong>Work Order Ref:</strong> WO-<%= String(auctionId).substring(0, 8).toUpperCase() %></p>
            </div>
            <div class="details" style="text-align: right;">
                <p><strong>Generated by:</strong> EcoLoop / We Connect</p>
            </div>
        </div>

        <div class="section">
            <div class="section-title">1. Contracting Parties</div>
            <div style="display: flex; justify-content: space-between;">
                <div class="details">
                    <p><strong>Client (Generator):</strong><br/> <%= clientName %></p>
                </div>
                <div class="details">
                    <p><strong>Vendor (Recycler):</strong><br/> <%= vendorName %><br/> <%= vendorAddress %></p>
                </div>
            </div>
        </div>

        <div class="section">
            <div class="section-title">2. Lot Details</div>
            <table>
                <tr>
                    <th>Description</th>
                    <th>Weight (Est.)</th>
                    <th>Final Winning Amount</th>
                </tr>
                <tr>
                    <td><%= auctionTitle %></td>
                    <td><%= totalWeight %> Kg</td>
                    <td>₹ <%= winningAmount.toLocaleString('en-IN') %></td>
                </tr>
            </table>
        </div>

        <div class="section">
            <div class="section-title">3. Terms & Conditions</div>
            <ul>
                <li>The Vendor agrees to pick up the material within 7 working days.</li>
                <li>The Vendor must provide a valid Pickup Challan at the time of material handover.</li>
                <li>The Vendor is strictly bound to process the e-waste in compliance with CPCB guidelines.</li>
                <li>The Vendor must upload the final E-Waste Recycling Certificate to the EcoLoop portal to close the EPR loop.</li>
            </ul>
        </div>

        <div class="signature-box">
            <div>
                <div class="sign-line">Authorized Signatory (Client)</div>
            </div>
            <div>
                <div class="sign-line">Authorized Signatory (Vendor)</div>
            </div>
        </div>

        <div class="footer">
            This is a digitally generated Work Order created by the EcoLoop Platform upon the conclusion of a verified auction.
        </div>
    </body>
    </html>
    `;

    const compiledHtml = ejs.render(htmlContent, {
      auctionId,
      clientName,
      vendorName,
      vendorAddress: vendorAddress || 'Address on file',
      auctionTitle,
      totalWeight: totalWeight || 0,
      winningAmount,
    });

    let browser;
    try {
      browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      });
      const page = await browser.newPage();
      await page.setContent(compiledHtml, { waitUntil: 'networkidle0' });
      
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' },
      });

      const s3Key = `work-orders/${auctionId}/WO-${Date.now()}.pdf`;
      
      const file: Express.Multer.File = {
        fieldname: 'file',
        originalname: `WO-${auctionId}.pdf`,
        encoding: '7bit',
        mimetype: 'application/pdf',
        size: pdfBuffer.length,
        buffer: Buffer.from(pdfBuffer),
        stream: null as any,
        destination: '',
        filename: '',
        path: '',
      };

      const { key } = await this.s3.upload(file, `work-orders/${auctionId}`);
      
      this.logger.log(`Successfully generated and uploaded Work Order: ${key}`);
      return key;
    } catch (error) {
      this.logger.error('Failed to generate Work Order PDF', error);
      throw error;
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }
}