-- Add bank details columns to Company table
ALTER TABLE "Company"
  ADD COLUMN IF NOT EXISTS "bankAccountHolder" TEXT,
  ADD COLUMN IF NOT EXISTS "bankName"          TEXT,
  ADD COLUMN IF NOT EXISTS "bankAccountNumber" TEXT,
  ADD COLUMN IF NOT EXISTS "bankIfscCode"      TEXT,
  ADD COLUMN IF NOT EXISTS "bankAccountType"   TEXT;

-- Add new DocumentType enum values
-- NOTE: ALTER TYPE ADD VALUE cannot run inside a transaction (Postgres restriction).
-- Apply with: psql -c "ALTER TYPE ..." or via psql interactive session.
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CERTIFICATE_OF_INCORPORATION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'COMPANY_PAN';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'DIRECTOR_PAN';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'AUTHORIZED_SIGNATORY_ID';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'BOARD_RESOLUTION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'KYC_FORM';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'EMD_PROOF';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'TERMS_ACCEPTANCE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'RECYCLER_LICENSE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'FACTORY_LICENSE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'BUSINESS_INSURANCE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'VENDOR_ONBOARDING_FORM';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'AUTHORIZATION_LETTER';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'ADDRESS_PROOF';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'E_WASTE_DECLARATION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'AADHAR_CARD';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CANCELLED_CHEQUE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'OTHER';
