"use client";

import { useState } from "react";
import { useApp } from "@/context/AppContext";

const STATUS_STEPS = [
  { key: 'pending', label: 'Pending', icon: 'hourglass_empty' },
  { key: 'created', label: 'Docs Sent', icon: 'send' },
  { key: 'acknowledged', label: 'Acknowledged', icon: 'verified' },
];

function printHandover(listing: any, clientName: string) {
  const w = window.open('', '_blank');
  if (!w) return;
  const html = `<!DOCTYPE html><html><head><title>Handover Documents - ${listing.id}</title>
<style>
  body { font-family: Arial, sans-serif; padding: 40px; color: #111; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  .header { border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }
  .section { margin-bottom: 20px; }
  .section h3 { font-size: 13px; text-transform: uppercase; color: #2563eb; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-bottom: 10px; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 8px 12px; font-size: 13px; border: 1px solid #e5e7eb; }
  td:first-child { font-weight: bold; width: 40%; background: #f8fafc; }
  .sig { margin-top: 60px; display: flex; justify-content: space-between; }
  .sig-box { border-top: 1px solid #111; width: 200px; text-align: center; padding-top: 8px; font-size: 12px; }
</style></head><body>
<div class="header">
  <h1>HANDOVER DOCUMENT / GATE PASS</h1>
  <p style="margin:0;color:#6b7280;font-size:13px;">WeConnect E-Waste Aggregator Platform</p>
  <p style="margin:4px 0 0;font-size:12px;color:#374151;">Issued by: ${clientName} &nbsp;|&nbsp; Date: ${listing.handoverDate ? new Date(listing.handoverDate).toLocaleDateString('en-IN') : new Date().toLocaleDateString('en-IN')}</p>
</div>
<div class="section">
  <h3>Material Details</h3>
  <table>
    <tr><td>Listing ID</td><td>${listing.id}</td></tr>
    <tr><td>Material Description</td><td>${listing.title}</td></tr>
    <tr><td>Category</td><td>${listing.category}</td></tr>
    <tr><td>Approximate Weight</td><td>${listing.weight} kg</td></tr>
    <tr><td>Pickup Location</td><td>${listing.pickupAddress || listing.location}</td></tr>
    <tr><td>Assigned Vendor</td><td>${listing.winnerVendorName || '—'}</td></tr>
  </table>
</div>
<div class="section">
  <h3>Gate Pass Details</h3>
  <table>
    <tr><td>Gate Pass Number</td><td>${listing.handoverGatePass || '—'}</td></tr>
    <tr><td>Pickup Date</td><td>${listing.handoverDate ? new Date(listing.handoverDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }) : '—'}</td></tr>
    <tr><td>Vehicle Number</td><td>${listing.handoverVehicle || '—'}</td></tr>
    <tr><td>Driver Name</td><td>${listing.handoverDriver || '—'}</td></tr>
    ${listing.handoverNotes ? `<tr><td>Notes</td><td>${listing.handoverNotes}</td></tr>` : ''}
  </table>
</div>
<div class="sig">
  <div class="sig-box">Client Authorized Signatory</div>
  <div class="sig-box">Vendor Representative</div>
  <div class="sig-box">Security / Gate Officer</div>
</div>
<p style="text-align:center;color:#9ca3af;font-size:11px;margin-top:40px;">Generated by WeConnect E-Waste Aggregator Platform</p>
</body></html>`;
  w.document.write(html);
  w.document.close();
  w.print();
}

export default function ClientHandoverPage() {
  const { currentUser, listings, createHandoverDocs } = useApp();
  const [createModal, setCreateModal] = useState<string | null>(null);
  const [form, setForm] = useState({ gatePass: '', vehicle: '', driver: '', date: '', notes: '' });
  const [submitting, setSubmitting] = useState(false);
  const [toast, setToast] = useState('');

  if (!currentUser) return null;

  const myListings = listings.filter(
    l => (l.userId === currentUser.id || l.userId === currentUser.companyId || l.userName === currentUser.name) && l.winnerVendorId
  ).filter(l => l.poStatus === 'acknowledged' || l.handoverStatus);

  const showToast = (msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(''), 3000);
  };

  const openCreate = (listingId: string, listing: any) => {
    setForm({
      gatePass: listing.handoverGatePass || `GP-${new Date().getFullYear()}-${Math.floor(Math.random() * 9000) + 1000}`,
      vehicle: listing.handoverVehicle || '',
      driver: listing.handoverDriver || '',
      date: listing.handoverDate ? listing.handoverDate.split('T')[0] : new Date().toISOString().split('T')[0],
      notes: listing.handoverNotes || '',
    });
    setCreateModal(listingId);
  };

  const handleSubmit = async () => {
    if (!createModal) return;
    if (!form.vehicle.trim() || !form.driver.trim() || !form.date) {
      showToast('Please fill in vehicle number, driver name, and pickup date.');
      return;
    }
    setSubmitting(true);
    createHandoverDocs(createModal, form);
    setSubmitting(false);
    setCreateModal(null);
    showToast('Handover documents sent to vendor successfully.');
  };

  const stepIndex = (status?: string) => STATUS_STEPS.findIndex(s => s.key === status);

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      {toast && (
        <div className="fixed top-6 right-6 z-50 bg-green-600 text-white px-5 py-3 rounded-xl shadow-lg text-sm font-bold">
          {toast}
        </div>
      )}

      <div>
        <h1 className="text-2xl font-black text-slate-900 dark:text-white">Handover Documents</h1>
        <p className="text-sm text-slate-500 mt-1">Create and send gate pass & delivery challan to the winning vendor for material pickup.</p>
      </div>

      {myListings.length === 0 ? (
        <div className="text-center py-20 text-slate-400">
          <span className="material-symbols-outlined text-5xl mb-3 block">inventory</span>
          <p className="font-bold">No handover documents yet.</p>
          <p className="text-sm">Handover documents become available once the Purchase Order is acknowledged by the vendor.</p>
        </div>
      ) : (
        <div className="space-y-5">
          {myListings.map(listing => {
            const currentStep = stepIndex(listing.handoverStatus || 'pending');

            return (
              <div key={listing.id} className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
                {/* Header */}
                <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800">
                  <div>
                    <p className="font-black text-slate-900 dark:text-white">{listing.title}</p>
                    <p className="text-xs text-slate-500">{listing.id} · Winner: {listing.winnerVendorName} · {listing.weight} kg</p>
                  </div>
                  <span className={`px-3 py-1 rounded-full text-xs font-bold capitalize ${
                    listing.handoverStatus === 'acknowledged' ? 'bg-green-100 text-green-700' :
                    listing.handoverStatus === 'created' ? 'bg-blue-100 text-blue-700' :
                    'bg-yellow-100 text-yellow-700'
                  }`}>
                    {listing.handoverStatus === 'acknowledged' ? 'Acknowledged' :
                     listing.handoverStatus === 'created' ? 'Docs Sent' : 'Pending'}
                  </span>
                </div>

                {/* Progress Steps */}
                <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-800">
                  <div className="flex items-center gap-0">
                    {STATUS_STEPS.map((step, i) => (
                      <div key={step.key} className="flex items-center flex-1 last:flex-none">
                        <div className="flex flex-col items-center">
                          <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                            i <= currentStep ? 'bg-green-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-400'
                          }`}>
                            <span className="material-symbols-outlined text-base">{i < currentStep ? 'check' : step.icon}</span>
                          </div>
                          <span className="text-[10px] font-bold mt-1 text-slate-500">{step.label}</span>
                        </div>
                        {i < STATUS_STEPS.length - 1 && (
                          <div className={`flex-1 h-0.5 mx-1 mb-4 ${i < currentStep ? 'bg-green-600' : 'bg-slate-200 dark:bg-slate-700'}`} />
                        )}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Handover details if created */}
                {listing.handoverStatus && listing.handoverStatus !== 'pending' && listing.handoverGatePass && (
                  <div className="px-6 py-4 bg-slate-50 dark:bg-slate-800/40">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                      <div>
                        <p className="text-xs text-slate-500 uppercase font-bold">Gate Pass</p>
                        <p className="font-black text-slate-900 dark:text-white mt-0.5">{listing.handoverGatePass}</p>
                      </div>
                      <div>
                        <p className="text-xs text-slate-500 uppercase font-bold">Pickup Date</p>
                        <p className="font-semibold text-slate-700 dark:text-slate-300 mt-0.5">
                          {listing.handoverDate ? new Date(listing.handoverDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}
                        </p>
                      </div>
                      <div>
                        <p className="text-xs text-slate-500 uppercase font-bold">Vehicle</p>
                        <p className="font-semibold text-slate-700 dark:text-slate-300 mt-0.5">{listing.handoverVehicle || '—'}</p>
                      </div>
                      <div>
                        <p className="text-xs text-slate-500 uppercase font-bold">Driver</p>
                        <p className="font-semibold text-slate-700 dark:text-slate-300 mt-0.5">{listing.handoverDriver || '—'}</p>
                      </div>
                    </div>
                    {listing.handoverNotes && (
                      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400 bg-white dark:bg-slate-900 rounded-lg p-3 border border-slate-200 dark:border-slate-700">
                        {listing.handoverNotes}
                      </p>
                    )}
                  </div>
                )}

                {listing.handoverStatus === 'acknowledged' && (
                  <div className="mx-6 my-3 p-3 bg-green-50 dark:bg-green-900/20 rounded-xl text-sm text-green-700 dark:text-green-300">
                    <span className="material-symbols-outlined text-base align-middle mr-1">verified</span>
                    Vendor has acknowledged receipt of handover documents. Pickup is scheduled.
                  </div>
                )}

                {/* Actions */}
                <div className="flex flex-wrap gap-3 px-6 pb-5">
                  {(!listing.handoverStatus || listing.handoverStatus === 'pending') && (
                    <button onClick={() => openCreate(listing.id, listing)}
                      className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-bold transition-colors flex items-center gap-2">
                      <span className="material-symbols-outlined text-base">send</span>
                      Create & Send Handover Docs
                    </button>
                  )}
                  {listing.handoverStatus === 'created' && (
                    <button onClick={() => openCreate(listing.id, listing)}
                      className="px-4 py-2 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 rounded-xl text-sm font-bold transition-colors flex items-center gap-2">
                      <span className="material-symbols-outlined text-base">edit</span>
                      Edit Documents
                    </button>
                  )}
                  {listing.handoverGatePass && (
                    <button onClick={() => printHandover(listing, currentUser.name)}
                      className="px-4 py-2 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 rounded-xl text-sm font-bold transition-colors flex items-center gap-2">
                      <span className="material-symbols-outlined text-base">download</span>
                      Download Gate Pass
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Create/Edit Modal */}
      {createModal && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl w-full max-w-lg">
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800">
              <h2 className="font-black text-slate-900 dark:text-white">Create Handover Documents</h2>
              <button onClick={() => setCreateModal(null)} className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800">
                <span className="material-symbols-outlined text-xl">close</span>
              </button>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">Gate Pass Number</label>
                  <input type="text" value={form.gatePass}
                    onChange={e => setForm(p => ({ ...p, gatePass: e.target.value }))}
                    className="w-full border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-sm bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">Pickup Date *</label>
                  <input type="date" value={form.date}
                    onChange={e => setForm(p => ({ ...p, date: e.target.value }))}
                    className="w-full border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-sm bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">Vehicle Number *</label>
                  <input type="text" placeholder="e.g. KA-01-AB-1234" value={form.vehicle}
                    onChange={e => setForm(p => ({ ...p, vehicle: e.target.value }))}
                    className="w-full border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-sm bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">Driver Name *</label>
                  <input type="text" placeholder="Full name" value={form.driver}
                    onChange={e => setForm(p => ({ ...p, driver: e.target.value }))}
                    className="w-full border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-sm bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none" />
                </div>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">Notes / Instructions</label>
                <textarea rows={3} placeholder="Any special instructions for the vendor..." value={form.notes}
                  onChange={e => setForm(p => ({ ...p, notes: e.target.value }))}
                  className="w-full border border-slate-200 dark:border-slate-700 rounded-xl px-3 py-2 text-sm bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none resize-none" />
              </div>
            </div>
            <div className="flex gap-3 px-6 pb-6">
              <button onClick={() => setCreateModal(null)}
                className="flex-1 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 text-sm font-bold text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800">
                Cancel
              </button>
              <button onClick={handleSubmit} disabled={submitting}
                className="flex-1 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-sm font-bold disabled:opacity-50 flex items-center justify-center gap-2">
                <span className="material-symbols-outlined text-base">send</span>
                {submitting ? 'Sending…' : 'Send to Vendor'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
